config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get "/custom_sign_out" => "devise/sessions#destroy", as: :custom_destroy_user_session
  end

  resources :groups do
    resources :payments
  end
  
  resources :labels
  resources :payments
  
  # root "groups#index"
  root 'static#welcome'

  get '/groups_home', to: 'groups#index', as: 'groups_home'

end

app/models/label.rb
class Label < ApplicationRecord
  belongs_to :user
  has_many :payments, dependent: :destroy
end

app/controllers/labels_controller.rb
class LabelsController < ApplicationController
  # Devise authentication
  before_action :authenticate_user!

  # cancan authorization
  #  load_and_authorize_resource

  # Set label
  before_action :set_label, only: %i[show edit update destroy]

  # GET /labels of current_user
  def index
    @labels = current_user.labels
  end

  # GET /labels/1 or /labels/1.json
  def show; end

  # GET /labels/new
  def new
    @label = Label.new
  end

  # GET /labels/1/edit
  def edit; end

  # POST /labels or /labels.json
  def create
    @label = Label.new(label_params)
    @label.user_id = current_user.id

    authorize! :create, @label

    respond_to do |format|
      if @label.save
        format.html { redirect_to labels_url, notice: 'label was successfully created.' }
        format.json { render :show, status: :created, location: @label }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @label.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /labels/1 or /labels/1.json
  def update
    authorize! :update, @label

    respond_to do |format|
      if @label.update(label_params)
        format.html { redirect_to labels_url, notice: 'label was successfully updated.' }
        format.json { render :show, status: :ok, location: @label }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @label.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /labels/1 or /labels/1.json
  def destroy
    authorize! :destroy, @label

    @label.destroy

    respond_to do |format|
      format.html { redirect_to labels_url, notice: 'label was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_label
    @label = Label.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def label_params
    params.require(:label).permit(:name)
  end
end

app/helpers/label_helper.rb
module LabelHelper
end

app/helpers/labels_helper.rb
module LabelsHelper
end

app/views/labels/_form.html.erb
<%= form_with(model: label, class: "form-data") do |form| %>
  <div "data-section">
    <div class="form-field-cnt">
      <%= form.label :name, class:'form-field-label width-sm' %>
      <%= form.text_field :name, class: 'form-field-input', autofocus: true %>
    </div>
  </div>

  <% if label.errors.any? %>
    <div class='center' style="color: red">
      <h3>Category could not be saved, enter a Name and select an Icon</h3>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit "Save changes", class: "format-btn-submit" %>
  </div>

<% end %>

app/views/labels/edit.html.erb
<div class='container flex-col data-wrapper'>
  <h1>Editing label</h1>

  <%= render "form", label: @label %>

  <div class='container'>
    <div class="actions-2">
      <%= link_to "< Back", labels_path %>
    </div>
  </div>
</div>

app/views/labels/index.html.erb
<div class='container flex-col'>
  <h1>Labels</h1>

  <div id="labels", class="data-wrapper">
    <% @labels.each do |label| %>
      <div class="label-cnt row">
        <div class="label-name">
          <%= label.name %>
        </div>
        <div class = "label-actions">
          <%= link_to "Edit", edit_label_path(label) %>
        </div>
      </div>
    <% end %>
  </div>

  <div class="actions">
    <%= link_to "New label", new_label_path, class: "format-btn-submit" %>
  </div>
</div>

app/views/labels/new.html.erb
<div class='container flex-col'>
  <h1>New label</h1>

  <%= render "form", label: @label %>

  <div class="container padding-lr-2">
    <div class="actions-2">
      <%= link_to "< Back", labels_path, class: "format-btn-submit" %>
    </div>
  </div>
</div>

app/views/labels/show.html.erb
<p style="color: green"><%= notice %></p>

 <p>
    <strong>Name:</strong>
    <%= @label.name %>
  </p>

<div>
  <%= link_to "Edit this label", edit_label_path(@label) %> |
  <%= link_to "Back to labels", labels_path %>

  <%= button_to "Destroy this label", @label, method: :delete %>
</div>