config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get "/custom_sign_out" => "devise/sessions#destroy", as: :custom_destroy_user_session
  end

  resources :groups do
    resources :payments
  end
  
  resources :labels
  resources :payments
  
  # root "groups#index"
  root 'static#welcome'

  get '/groups_home', to: 'groups#index', as: 'groups_home'

end

app/models/group.rb
class Group < ApplicationRecord
  validates :name, presence: true
  validates :icon, presence: true
  belongs_to :user
  has_many :payments, dependent: :destroy
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  # Devise authentication
  before_action :authenticate_user!

  # cancan authorization
  #  load_and_authorize_resource

  # Set group
  before_action :set_group, only: %i[show edit update destroy]

  # GET /groups of current_user
  def index
    @groups = current_user.groups
      .left_joins(:payments)
      .select('groups.id, groups.name, groups.icon, SUM(payments.amount) as total_amount')
      .group('groups.id, groups.name, groups.icon')
      .order('groups.created_at')

    # replace nil with 0
    @groups.each do |group|
      group.total_amount ||= 0
    end
  end

  # select the payments of the group
  def show
    @group = Group.find(params[:id])
    @payments = @group.payments.order('created_at DESC')
  end

  # GET /groups/new
  def new
    create_icon_names
    @group = Group.new
    @group.icon = @icon_names[0] # set default icon
    @selected_icon = @group.icon
  end

  # GET /groups/1/edit
  def edit
    create_icon_names
    @selected_icon = @group.icon
    @group
  end

  # POST /groups or /groups.json
  def create
    create_icon_names
    @group = Group.new(group_params)
    @group.user_id = current_user.id

    authorize! :create, @group

    respond_to do |format|
      if @group.save
        format.html { redirect_to groups_url, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1 or /groups/1.json
  def update
    create_icon_names
    @group.user_id = current_user.id

    authorize! :update, @group

    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to groups_url, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1 or /groups/1.json
  def destroy
    authorize! :destroy, @group
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_group
    @group = Group.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def group_params
    params.require(:group).permit(:name, :icon, :user_id)
  end

  # Create icon names for select
  def create_icon_names
    @icon_names = []
    Dir.glob('app/assets/images/caticons/*.png').each do |file|
      @icon_names << ("#{File.basename(file, '.png')}.png")
    end
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_edit.html.erb
<%= form_with(model: group,   url: group_path(@group), class: "form-data", local: true) do |form| %>
  <div "data-section">
    <div class="form-field-cnt">
      <%= form.label "Name:", class:'form-field-label width-sm' %>
      <%= form.text_field :name, placeholder: "Category's name", class: 'form-field-input', autofocus: true %>
    </div>

    <div class="form-field-cnt">
      <%= form.label "Icon:", class: 'form-field-label width-sm' %>
      <%= form.hidden_field :icon, id: 'selected-icon', value: '' %>

      <div class="icon-select">
        <% @icon_names.map do |i| %>
          <div class="icon-cnt">
            <div class="icon-label">
              <%= form.radio_button :icon, i, class: 'icon-option', required: true, onchange: 'selectIcon(this)' %>
              <%= label_tag "icon_#{i}" do %>
                <%= image_tag "caticons/#{i}", class: 'category-icon' %>
              <% end %>
            </div>          
          </div>
        <% end %>
      </div>
    </div>

  </div>

  <% if group.errors.any? %>
    <div class='center' style="color: red">
      <h3>Category could not be saved, enter a Name and select an Icon</h3>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit "Save changes", class: "format-btn-submit" %>
  </div>
<% end %>

app/views/groups/_form.html.erb
<%= form_with(model: group,   url: groups_path(@group), class: "form-data", local: true) do |form| %>
  <div "data-section">
    <div class="form-field-cnt">
      <%= form.label "Name:", class:'form-field-label width-sm' %>
      <%= form.text_field :name, placeholder: "Category's name", class: 'form-field-input', autofocus: true %>
    </div>
    
    <div class="form-field-cnt">
      <%= form.label "Icon:", class: 'form-field-label width-sm' %>
      <%= form.hidden_field :icon, id: 'selected-icon', value: '' %>

      <div class="icon-select">
        <% @icon_names.map do |i| %>
          <div class="icon-cnt">
            <div class="icon-label">
              <%= form.radio_button :icon, i, class: 'icon-option', required: true, onchange: 'selectIcon(this)' %>
              <%= label_tag "icon_#{i}" do %>
                <%= image_tag "caticons/#{i}", class: 'category-icon' %>
              <% end %>
            </div>          
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <% if group.errors.any? %>
    <div class='center' style="color: red">
      <h3>Category could not be saved, enter a Name and select an Icon</h3>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit "Save changes", class: "format-btn-submit" %>
  </div>
<% end %>

app/views/groups/_group.html.erb
<div id="<%= dom_id group %>">
  <a href="<%= group_path(group) %>">
    <div class='row border group-card'>
      <div class='icon-cnt'>
        <%= image_tag "caticons/#{group.icon}", class: 'category-icon' %>
      </div>
        <strong>
          <%= group.name %>
        </strong>
      </p>

      <div class="flex-col group-amount">
        <strong>Total</strong>
        <%= number_to_currency(group.total_amount, unit: "$", precision: 2) %>
      </div>
    </div>
  </a>
</div>

app/views/groups/edit.html.erb
<div class='container flex-col data-wrapper'>
  <h1>Editing category</h1>

  <%= render "edit", group: @group %>

  <div class='container'>
    <div class="actions-2">
      <%= link_to "Back", groups_path %>
    </div>
  </div>
</div>

app/views/groups/index.html.erb
<div class='container flex-col'>
  <h1>Categories</h1>

  <div id="groups" class="cnt-scrollable max-height-md">
    <% @groups.each do |group| %>
      <%= render group %>
    <% end %>
  </div>

  <div class="actions">
    <%= link_to "New Category", new_group_path, class: "format-btn-submit" %>
  </div>
</div>

app/views/groups/new.html.erb
<div class='container flex-col'>
  <h1>Add Category</h1>
  <div id="groups" class="cnt-scrollable data-wrapper">
    <%= render "form", group: @group %>
  </div>

  <div class="container padding-lr-2">
    <div class="actions-2">
      <%= link_to "< Back", groups_path, class: "format-btn-submit" %>
    </div>
  </div>
</div>

app/views/groups/show.html.erb
<div class='container flex-col'>
  <div class='payments-group-card max-height-lg'>
    <h3>Payments for Category</h3>
    <h2><%= @group.name %></h2>
    <div class='row group-header'>
      <div class='icon-cnt'>
        <%= image_tag "caticons/#{@group.icon}", class: 'category-icon' %>
      </div>

      <div class="flex-col group-amount">
        <strong>Total Amount</strong>
        <strong>
          <%= number_to_currency(@group.payments.sum(:amount), unit: "$", precision: 2) %>
        </strong>
      </div>
    </div>


    <div id="groups" class="cnt-scrollable max-height-md">
      <% @payments.each do |payment| %>
        <div class = 'payment-detail row'>
          <div class = 'payment-name-date'>
            <div class = 'payment-name'>
              <%= payment.label.name %>
            </div>
            <div class = 'payment-date'>
              <%= payment.created_at.strftime("%a, %d %b %y (%I:%M%p)") %>
            </div>
          </div>
          <div class = 'payment-amount'>
            <%= number_to_currency(payment.amount, unit: "$", precision: 2) %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  
  <div class= 'welcome-buttons'>
    <div class="actions">
      <%= link_to "Add transaction", new_group_payment_path(@group), class: "format-btn-submit"  %>
    </div>
    <div class="actions-2">
      <%= link_to "< Back", groups_path, class: "format-btn-submit"  %>
    </div>
  </div>
</div>