config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get "/custom_sign_out" => "devise/sessions#destroy", as: :custom_destroy_user_session
  end

  resources :groups do
    resources :payments
  end
  
  resources :labels
  resources :payments
  
  # root "groups#index"
  root 'static#welcome'

  get '/groups_home', to: 'groups#index', as: 'groups_home'

end

app/views/shared/_header.html.erb
<div class="navbar">
  <nav class="navbar-nav">
    <ul class="navbar-ul">
      <div class="menu-btn-cnt invert-color">
        <%= image_tag("menu-icon.svg", class:'menu-btn') %>
    </ul>
    <ul class="navbar-ul">
      <% if user_signed_in? %>
        <span class="circle-badge text-bg-info">
          <%= current_user.name.split(' ').map { |word| word[0] }.join.upcase %>
          's
        </span>
      <% end %>
      <span class="font-logo">Journey Cash</span>
    </ul>
  </nav>
</div>
  
<div class="overlay">
</div>

<div class="navbar-menu">
  <div class="menu-close">
    <%= image_tag("close-icon.svg", class:'menu-btn invert-color') %>
  </div>
  <% if user_signed_in? %>
    <div class='user-info'>
      <div class="profile-icon">
        <%= image_tag("user-icon.svg", class:'user-icon invert-color') %>
      </div>
      <span class="lbl-username">
        <%= current_user.name.upcase %>
      </span>
    </div>
    <%= link_to groups_home_path, :method => :get, class:'navbar-li menu-exit' do %>
      <%= image_tag("groups-icon.svg", class:'nav-icon menu-exit') %> Categories
    <% end %>
    <div class="divider"></div>
    <%= link_to new_group_path(current_user.id), class:'navbar-li' do %>
      <%= image_tag("add-group-icon.svg", class:'nav-icon') %> New category
    <% end %>
    <div class="divider"></div>
    <%= link_to labels_path(current_user.id), class:'navbar-li' do %>
      <%= image_tag("labels-icon.svg", class:'nav-icon') %> Labels
    <% end %>
    <div class="divider"></div>
    <%= link_to edit_user_registration_path(current_user.id), class:'navbar-li' do %>
      <%= image_tag("settings-icon.svg", class:'nav-icon') %> Account Settings 
    <% end %>
    <div class="divider"></div>
    <%= link_to custom_destroy_user_session_path, method: :delete, class:'navbar-li menu-exit' do %>
      <%= image_tag("logout-icon.svg", class:'nav-icon menu-exit') %> Log Out
    <% end %>
  <% else  %>
    <%= link_to new_user_session_path, class:'navbar-li' do %>
      <%= image_tag("user-icon.svg", class:'nav-icon') %> Sign in 
    <% end %>
    <div class="divider"></div>
    <%= link_to new_user_registration_path, class:'navbar-li' do %>
      <%= image_tag("new-user-icon.svg", class:'nav-icon') %> Register 
    <% end %>
  <% end %>
</div>

<div class="alerts">
  <% if notice.present? %>
    <p class="alerts-text"><%= notice %></p>
  <% end %>
  <% if alert.present? %>
    <p class="alerts-text"><%= alert %></p>
  <% end %>
</div>