config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get "/custom_sign_out" => "devise/sessions#destroy", as: :custom_destroy_user_session
  end

  resources :groups do
    resources :payments
  end
  
  resources :labels
  resources :payments
  
  # root "groups#index"
  root 'static#welcome'

  get '/groups_home', to: 'groups#index', as: 'groups_home'

end

app/models/payment.rb
class Payment < ApplicationRecord
  validates :amount, presence: true, numericality: { greater_than: 0 }
  validates :label, presence: true
  validates :group, presence: true

  belongs_to :label
  belongs_to :group
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  # Devise authentication
  before_action :authenticate_user!
  before_action :set_payment, only: %i[show edit update destroy]
  before_action :find_group, only: %i[new create]

  # GET /payments or /payments.json
  def index
    # get all payments from the current user, from most recent to oldest
    @payments = Payment.where(group_id: current_user.groups).order(created_at: :desc)
  end

  # GET /payments/1 or /payments/1.json
  def show; end

  # GET /payments/new
  def new
    @payment = Payment.new
    @group = Group.find(params[:group_id])
    @payment.group_id = params[:group_id]

    create_label_names
  end

  # GET /payments/1/edit
  def edit; end

  # POST /payments or /payments.json
  def create
    create_label_names
    @payment = Payment.new(payment_params)
    @payment.group_id = params[:payment][:group_id]

    validate_label

    authorize! :create, @payment

    respond_to do |format|
      if @payment.save
        format.html { redirect_to group_path(@payment.group), notice: 'Payment was successfully created.' }
        format.json { render :show, status: :created, location: @payment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payments/1 or /payments/1.json
  def update
    respond_to do |format|
      validate_label

      authorize! :update, @payment

      if @payment.update(payment_params)
        format.html { redirect_to payment_url(@payment), notice: 'Payment was successfully updated.' }
        format.json { render :show, status: :ok, location: @payment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1 or /payments/1.json
  def destroy
    authorize! :destroy, @payment

    @payment.destroy

    respond_to do |format|
      format.html { redirect_to payments_url, notice: 'Payment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def find_group
    @group = Group.find(params[:group_id])
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_payment
    @payment = Payment.find(params[:id])
  end

  def create_label_names
    @labels = current_user.labels.order(:name).to_a
    @label = [] if @labels.blank?
    # add a "create new label" option to the array of labels
    @labels << { id: '#new*', name: 'Create a new label' }
  end

  # Only allow a list of trusted parameters through.
  def payment_params
    params.require(:payment).permit(:group_id, :amount)
  end

  def validate_label
    # Verify if select a existing label or create a new one
    if params[:payment][:label_id].present? && params[:payment][:label_id] != '#new*'
      @payment.label_id = params[:payment][:label_id]
    else
      new_label_name = params[:payment][:new_label]

      # Verify if the new label name is not empty
      if new_label_name.present?
        # look for a label with the same name
        new_label_name = new_label_name.capitalize
        existing_label = Label.find_by(name: new_label_name)

        if existing_label
          # if exist a label with the same name, use it
          @payment.label_id = existing_label.id
        else
          # if not exist a label with the same name, create a new one
          new_label = Label.create(name: new_label_name, user_id: current_user.id)
          @payment.label_id = new_label.id
        end
      end
    end
  end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/_form.html.erb
<%= form_with(model: payment, url: group_payments_path(@group), class: "form-data", local: true) do |form| %>

  <div "data-section">

    <h3 class='center'>for Category</h3>
    <div class='row container center '>
      <div class='icon-cnt'>
        <%= image_tag "caticons/#{@group.icon}", class: 'category-icon' %>
      </div>
      <strong>
        <%= @group.name %>
      </strong>
      <%= form.hidden_field :group_id, value: @group.id %>
    </div>

    <div class="form-field-cnt">
      <p>Label</p>
      <%= form.select :label_id, options_for_select(@labels.pluck(:name, :id),
          payment.label_id), { include_blank: 'Select a label' },
          { data: { new_option: true }, id: 'label_id_select', class: 'form-field-input' } %>  
    </div>

    <div id='new_label' class="form-field-cnt" >
      <%= form.label :new_label, 'New label', class:'form-field-label width-sm' %>
      <%= form.text_field :new_label, class: 'form-field-input'  %>
    </div>

    <div class='form-field-cnt'>
      <%= form.label :amount, "Amount", style: "display: block", class:'form-field-label width-sm' %>
      <%= form.text_field :amount, input_html: { type: "number" }, class: "currency-input form-field-input"  %>
    </div>
  </div>

  <% if payment.errors.any? %>
    <div class='center' style="color: red">
      <strong>Payment could not be saved, please fill in all fields</strong>
    </div>
  <% end %>
  <div class="actions">
    <%= form.submit "Save transaction", class: "format-btn-submit" %>
  </div>
<% end %>

app/views/payments/_formwithgroup.html.erb
<%= form_with(model: payment, class: "form-data", url: groups_path) do |form| %>
  <div "data-section">
    <% if payment.errors.any? %>
      <div style="color: red">
        <h2>Payment could not be saved, please fill in all fields</h2>
        <ul>
          <% payment.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
      </div>
    <% end %>

    <div  class="form-field-cnt">
      <%= form.label "Group" %>
      <%= form.select :group_id, options_for_select(Group.order(:name).pluck(:name, :id), 
            payment.group_id), { include_blank: 'Select a Group' },
            { class: 'form-field-input' } %>
    </div>

    <div class="form-field-cnt">
      <%= form.label "Label" %>
      <%= form.select :label_id, options_for_select(Label.order(:name).pluck(:name, :id),
          payment.label_id), { include_blank: 'Select a label' },
          { data: { new_option: true }, id: 'label_id_select', class: 'form-field-input' } %>  
    </div>

    <div id='new_label' class="form-field-cnt" style="display: none" >
      <%= form.label :new_label, 'New label', class:'form-field-label width-sm' %>
      <%= form.text_field :new_label, class: 'form-field-input'  %>
    </div>

    <div class='form-field-cnt'>
      <%= form.label "Amount", style: "display: block", class:'form-field-label width-sm' %>
      <%= form.text_field :amount, input_html: { type: "number" }, class: "currency-input form-field-input"  %>
    </div>
  </div>

  <div class="actions">
    <%= form.submit "Save transaction", class: "format-btn-submit" %>
  </div>
<% end %>

app/views/payments/_payment.html.erb
<div id="<%= dom_id payment %>">
  <p>
    <strong>Group:</strong>
    <%= payment.group.name %>
  </p>

  <p>
    <strong>Label:</strong>
    <%= payment.label.name %>
  </p>

  <p>
    <strong>Amount:</strong>
    <%= payment.amount %>
  </p>

</div>

app/views/payments/edit.html.erb
<%= javascript_include_tag 'customfield' %>

<h1>Editing payment</h1>

<%= render "form", payment: @payment %>

<br>

<div>
  <%= link_to "Show this payment", @payment %> |
  <%= link_to "Back to payments", payments_path %>
</div>

app/views/payments/index.html.erb
<div class='container flex-col'>
  <h1>Payments</h1>

  <div id="payments">
    <% @payments.each do |payment| %>
      <%= render payment %>
      <p>
        <%= link_to "Show this payment", payment %>
      </p>
    <% end %>
  </div>

  <div class="actions">
    <%= link_to "New payment", new_payment_path, class: "format-btn-submit" %>
  </div>
</div>

app/views/payments/new.html.erb
<div class='container flex-col'>
  <h1>New transaction</h1>

  <div id="groups" class="cnt-scrollable data-wrapper">
    <%= render "form", payment: @payment %>
  </div>

  <div class="container padding-lr-2">
    <div class="actions-2">
      <%= link_to "< Back", group_path(@payment.group), class: "format-btn-submit" %>
    </div>
  </div>

</div>

app/views/payments/newwithgroup.html.erb
<%= javascript_include_tag 'customfield' %>

<div class='container flex-col'>
  <h1>New transaction</h1>

  <div id="groups" class="cnt-scrollable data-wrapper">
    <%= render "formwithgroup", payment: @payment %>
  </div>

  <div class="container padding-lr-2">
    <div class="actions-2">
      <%= link_to "< Back", groups_path, class: "format-btn-submit" %>
    </div>
  </div>

</div>

app/views/payments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @payment %>

<div>
  <%= link_to "Edit this payment", edit_payment_path(@payment) %> |
  <%= link_to "Back to payments", payments_path %>

  <%= button_to "Destroy this payment", @payment, method: :delete %>
</div>